# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          [[ -d bin ]] || mkdir bin
          [[ -d lib ]] || mkdir lib
          curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
          curl https://repo1.maven.org/maven2/jfree/jcommon/1.0.5/jcommon-1.0.5.jar -o lib/jcommon-1.0.5.jar
          curl https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar -o lib/javax.servlet-api-4.0.1.jar
          curl https://repo1.maven.org/maven2/org/mockito/mockito-all/2.0.2-beta/mockito-all-2.0.2-beta.jar -o lib/mockito-all-2.0.2-beta.jar
          javac -d bin/ -cp lib/jcommon-1.0.5.jar:lib/javax.servlet-api-4.0.1.jar:lib/mockito-all-2.0.2-beta.jar $(find jFreeChart_A3/src/ -name "*.java")
          javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar:lib/jcommon-1.0.5.jar:lib/mockito-all-2.0.2-beta.jar $(find jFreeChart_A3/test/ -name "*.java")
          java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path


